name: Run acceptance tests

on: pull_request

jobs:
  browserstack_acceptance:
    name: Browserstack Acceptance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: ./.github/run_browserstack_acceptance.sh
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          GITHUB_BRANCH: ${{ GITHUB_BRANCH }}-regular
